import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import registerServiceWorker from './registerServiceWorker';
//import App from './App';
//import Ch2 from './Ch2/Ch2';
//import Ch3 from './Ch3/Ch3';
//import Ch4 from './Ch4/Ch4';
//import Ch5 from './Ch5/Ch5';
//import Ch6 from "./Ch6/Ch6";
//import Ch9 from "./Ch9/Ch9";
//import Ch10 from "./Ch10/Ch10";
import Ch13 from "./Ch13/containers/Ch13";
import { createStore } from "redux";
import reducers from './Ch13/reducers';
import { Provider } from 'react-redux';
//const store = createStore(reducers);
const store = createStore(reducers, window.devToolsExtension && window.devToolsExtension());

ReactDOM.render(<Provider store={store}><Ch13/></Provider>, document.getElementById('root'));
//ReactDOM.render(<Ch10/>, document.getElementById('root'));
//ReactDOM.render(<Ch9/>, document.getElementById('root'));
//ReactDOM.render(<Ch6/>, document.getElementById('root'))
//ReactDOM.render(<Ch5/>, document.getElementById('root'));
//ReactDOM.render(<Ch4/>, document.getElementById('root'));
//ReactDOM.render(<Ch3 name="Ch3" age={20} />, document.getElementById('root1'));
//ReactDOM.render(<Ch3/>, document.getElementById('root'));
//ReactDOM.render(<Ch2/>, document.getElementById('root'));
//ReactDOM.render(<App/>, document.getElementById('root'));
registerServiceWorker();
